GET http://127.0.0.1:200/line/webhook

###

GET http://127.0.0.1:200/facebook/webhook

###

POST http://080a600dd776.ngrok.io/signup
Content-Type: application/json

{"birthday": "2021-01-11",
"email": "tanathep.min@gmail.com",
"firstname": "Tanathep",
"lastname": "Roongpipat",
"password": "1234",
"shop_address": "asdsfga",
"shop_name": "sdfgfdg",
"shop_type": "fdgdfbdf",
"username": "neroswords"}